version: "1.5"
namespace:
    key: default
    name: Default
flags:
    - key: testing
      name: testing
      type: VARIANT_FLAG_TYPE
      enabled: false
      variants:
        - default: true
          key: test
          attachment: {}
