version: "1.5"
namespace:
    key: default
    name: Default
flags:
    - key: proceed-to-checkout-color
      name: proceed-to-checkout-color
      type: VARIANT_FLAG_TYPE
      enabled: true
      variants:
        - key: green
          attachment: {}
        - key: red
          attachment: {}
        - key: blue
          attachment: {}
      rules:
        - segment:
            keys:
                - demo-segment
            operator: OR_SEGMENT_OPERATOR
          distributions:
            - variant: green
              rollout: 33.34
            - variant: red
              rollout: 33.33
            - variant: blue
              rollout: 33.33
segments:
    - key: demo-segment
      name: Beta User
      match_type: ALL_MATCH_TYPE
